[build]
  publish   = "."
  functions = "netlify/functions"

# 1️⃣ Proxy /api/* → your Netlify functions
[[redirects]]
  from      = "/api/*"
  to        = "/.netlify/functions/:splat"
  status    = 200

# 2️⃣ Serve your success page
[[redirects]]
  from      = "/success"
  to        = "/success/index.html"
  status    = 200
  force     = true

# 3️⃣ SPA fallback for everything else
[[redirects]]
  from      = "/*"
  to        = "/index.html"
  status    = 200
