[build]
  # your publish dir, adjust if needed:
  publish = "."

[[redirects]]
  # 1️⃣ First match /success (with or without data query)
  from   = "/success"
  to     = "/success/index.html"
  status = 200
  force  = true

[[redirects]]
  # 2️⃣ Then your SPA fallback
  from   = "/*"
  to     = "/index.html"
  status = 200
