[build]
  # This explicitly tells Netlify where your serverless functions are.
  functions = "netlify/functions"
  
  # This explicitly tells Netlify that the root directory contains your site.
  publish = "/"
