# Netlify configuration file

[build]
  # Directory where Netlify publishes your site
  publish = "."
  # Directory where Netlify looks for Functions
  functions = "netlify/functions"

# Redirect /success to the success page with your signature builder
[[redirects]]
  from   = "/success"
  to     = "/success/index.html"
  status = 200
  force  = true

# SPA fallback for all other routes
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
