[build]
  publish    = "."                   # or your actual publish directory
  functions  = "netlify/functions"

# 1) First, serve success.html normally
[[redirects]]
  from   = "/success.html"
  to     = "/success.html"
  status = 200
  force  = true

# 2) Then catch-all for your SPA
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
